<a href="https://colab.research.google.com/github/simantishwar/OIBSIP/blob/main/Task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('Carprice.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [4]:
print(df['cylindernumber'].unique())
df['cylindernumber'] = df['cylindernumber'].replace({'four':4, 'six':6, 'five':5, 'three':3, 'twelve':12, 'two':2, 'eight':8})

['four' 'six' 'five' 'three' 'twelve' 'two' 'eight']

In [5]:
print(df['doornumber'].unique())
df['doornumber'] = df['doornumber'].replace({'four':4, 'two':2})

['two' 'four']

In [6]:
df = df.drop(['car_ID','CarName'], axis=1)
df.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,gas,std,2,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,gas,std,4,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,gas,std,4,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [7]:
categories = df.select_dtypes('object').columns
categories

Index(['fueltype', 'aspiration', 'carbody', 'drivewheel', 'enginelocation',
       'enginetype', 'fuelsystem'],
      dtype='object')

In [8]:
y = df['price']
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

In [9]:
X = df.drop('price', axis=1)
X

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,...,4,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,3,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,...,4,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,1,gas,std,2,hatchback,rwd,front,94.5,171.2,65.5,...,6,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,2,gas,std,4,sedan,fwd,front,99.8,176.6,66.2,...,4,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,2,gas,std,4,sedan,4wd,front,99.4,176.6,66.4,...,5,136,mpfi,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,4,sedan,rwd,front,109.1,188.8,68.9,...,4,141,mpfi,3.78,3.15,9.5,114,5400,23,28
201,-1,gas,turbo,4,sedan,rwd,front,109.1,188.8,68.8,...,4,141,mpfi,3.78,3.15,8.7,160,5300,19,25
202,-1,gas,std,4,sedan,rwd,front,109.1,188.8,68.9,...,6,173,mpfi,3.58,2.87,8.8,134,5500,18,23
203,-1,diesel,turbo,4,sedan,rwd,front,109.1,188.8,68.9,...,6,145,idi,3.01,3.40,23.0,106,4800,26,27
204,-1,gas,turbo,4,sedan,rwd,front,109.1,188.8,68.9,...,4,141,mpfi,3.78,3.15,9.5,114,5400,19,25

In [10]:
X.head()

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,3,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,...,4,130,mpfi,3.47,2.68,9.0,111,5000,21,27
1,3,gas,std,2,convertible,rwd,front,88.6,168.8,64.1,...,4,130,mpfi,3.47,2.68,9.0,111,5000,21,27
2,1,gas,std,2,hatchback,rwd,front,94.5,171.2,65.5,...,6,152,mpfi,2.68,3.47,9.0,154,5000,19,26
3,2,gas,std,4,sedan,fwd,front,99.8,176.6,66.2,...,4,109,mpfi,3.19,3.40,10.0,102,5500,24,30
4,2,gas,std,4,sedan,4wd,front,99.4,176.6,66.4,...,5,136,mpfi,3.19,3.40,8.0,115,5500,18,22

In [11]:
X = pd.get_dummies(X)
X

,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,...,enginetype_ohcv,enginetype_rotor,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,3,2,88.6,168.8,64.1,48.8,2548,4,130,3.47,...,0,0,0,0,0,0,0,1,0,0
1,3,2,88.6,168.8,64.1,48.8,2548,4,130,3.47,...,0,0,0,0,0,0,0,1,0,0
2,1,2,94.5,171.2,65.5,52.4,2823,6,152,2.68,...,1,0,0,0,0,0,0,1,0,0
3,2,4,99.8,176.6,66.2,54.3,2337,4,109,3.19,...,0,0,0,0,0,0,0,1,0,0
4,2,4,99.4,176.6,66.4,54.3,2824,5,136,3.19,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,4,109.1,188.8,68.9,55.5,2952,4,141,3.78,...,0,0,0,0,0,0,0,1,0,0
201,-1,4,109.1,188.8,68.8,55.5,3049,4,141,3.78,...,0,0,0,0,0,0,0,1,0,0
202,-1,4,109.1,188.8,68.9,55.5,3012,6,173,3.58,...,1,0,0,0,0,0,0,1,0,0
203,-1,4,109.1,188.8,68.9,55.5,3217,6,145,3.01,...,0,0,0,0,0,1,0,0,0,0
204,-1,4,109.1,188.8,68.9,55.5,3062,4,141,3.78,...,0,0,0,0,0,0,0,1,0,0

In [12]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [13]:
X = pd.DataFrame(ss.fit_transform(X), columns=X.columns)
X.head()

,symboling,doornumber,wheelbase,carlength,carwidth,carheight,curbweight,cylindernumber,enginesize,boreratio,...,enginetype_ohcv,enginetype_rotor,fuelsystem_1bbl,fuelsystem_2bbl,fuelsystem_4bbl,fuelsystem_idi,fuelsystem_mfi,fuelsystem_mpfi,fuelsystem_spdi,fuelsystem_spfi
0,1.743470,-1.130388,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,-0.352887,0.074449,0.519071,...,-0.260208,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.08667,-0.214286,-0.070014
1,1.743470,-1.130388,-1.690772,-0.426521,-0.844782,-2.020417,-0.014566,-0.352887,0.074449,0.519071,...,-0.260208,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.08667,-0.214286,-0.070014
2,0.133509,-1.130388,-0.708596,-0.231513,-0.190566,-0.543527,0.514882,1.502032,0.604046,-2.404880,...,3.843076,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.08667,-0.214286,-0.070014
3,0.938490,0.884652,0.173698,0.207256,0.136542,0.235942,-0.420797,-0.352887,-0.431076,-0.517266,...,-0.260208,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.08667,-0.214286,-0.070014
4,0.938490,0.884652,0.107110,0.207256,0.230001,0.235942,0.516807,0.574572,0.218885,-0.517266,...,-0.260208,-0.141069,-0.23812,-0.689072,-0.121867,-0.328798,-0.070014,1.08667,-0.214286,-0.070014

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [16]:
model.fit(X_train, y_train)

LinearRegression()

In [17]:
pred = model.predict(X_test)
pred

array([ 6186.68650294,  6019.09172162, 20773.22439427, 32473.84927208,
        6976.29206542, 18351.09384046, 20920.48392368,  6715.88556292,
        8232.10801411,  9395.83982964,  6235.73737689,  6715.88556292,
        6217.28166857, 32940.51415623,  8864.2521052 , 10718.90741705,
       13528.47336717, 30344.62483756,  6949.79267023,  3811.51456655,
        7222.08113119, 10879.08763661,  8288.81108447, 19826.21343886,
        9716.5023554 ,  9566.27439026, 10379.58389311,  8349.03072498,
       18729.82533162,  7085.99438919, 11461.09523577,  5419.8577802 ,
       20891.76322102, 17413.40104869,  9564.29346802,  6004.63645109,
       13624.21253955, 34070.8265963 , 33708.65411076,  6948.76053682,
        7911.77821808, 12477.08750004, 11478.66325233,  3684.16258168,
       17184.02417134, 15931.22820513, 13475.48644051,  6062.56803365,
       37929.39801287, 21577.22598917,  5758.85145515,  7616.70277797,
       13624.21253955, 11072.41571359,  7042.61993382, 15628.06732302,
       11740.13212954, 14657.06057038, 13356.48574028,  9659.12394587,
       17410.12807067, 18400.64075155])

In [18]:
from sklearn.metrics import r2_score

accuracy = r2_score(y_test, pred) * 100
print("The model is {0:.2f}% accurate.".format(accuracy))

The model is 83.22% accurate.